### ISSUE TITLE
[Request] In fact a question: is it available for Linux?

### ISSUE THREAD

**Issue by cipricus** [AyrA/MakeMKV#1]
Can this be installed in Linux?

**Comment by AyrA** [comment]
No. The Windows version of MakeMKV stores the settings (and key) in the registry. The key updater has been specifically written for this use case. There's no equivalent to the Windows Registry on Linux. To make this work, you would need to find the file where MakeMKV stores the key and then change the registry key replacement mechanism in the tool for a file based one.
In other words, you need to change half of the application to make it work on Linux, at which point you may also just write your own.

If you find where the key is kept on your disk, you can fairly trivial write your own update utility by simply using the API from https://cable.ayra.ch/makemkv/

**Comment by OCsonic** [comment]
If you still need it, I just wrote a utility for this :P

https://codeberg.org/BasilBasil/MakeMKV-Keyscript

Just set it as user timer with systemd or a user cron job to run it automatically.

**Comment by AyrA** [comment]
I recommend you try to eliminate unnecessary requests. Use one of the API endpoints that delivers the key expiration date with it, and store this date locally, then you can skip making requests before the key is expired.

Also killing a process the user may be using is generally not a very nice thing to do.

**Comment by OCsonic** [comment]
> I recommend you try to eliminate unnecessary requests. Use one of the API endpoints that delivers the key expiration date with it, and store this date locally, then you can skip making requests before the key is expired.

Ah I didn't know the api provided that info, I'll switch from using the raw key to using the json endpoint, I gotta refresh my jq knowledge a bit lol :sweat_smile: 

> Also killing a process the user may be using is generally not a very nice thing to do.

Thats also a good catch, I completely forgot that if you ran that on a timer it could run when you're using MakeMKV :sweat:

I'll update it so that instead of just killing MakeMKV it will notify you when the active key is expired and then wait for MakeMKV to be killed by a user before updating the key, that should be a lot better :sweat_smile: should be easy to implement too
